### ISSUE TITLE
Add gitignore file

### ISSUE THREAD

**Issue by RayhanBaloch** [riad46/FavLocations#1]
You might consider adding the gitignore file. I looked through your repository and found that the Debug folder is also being kept in git. Each time you build your app the git will show changes to your file although no major changes are being made. Furthermore, the debug folder might contain some sensitive information that you might not want to share.

**Comment by riad46** [comment]
Thank you for the advice,
I added a .gitignore file and fixed the project files 
I hope that the issue is fixed
sorry for all the unnecessary commits
